### PR TITLE
implement basic netlify functions:list command

### PR DESCRIPTION
**Pull request by sw-yx**
**- Summary**

its small, people want to check that their functions are properly formatted. theres more potential for local validation (`functions doctor`?) generally.

closes https://github.com/netlify/netlify-dev-plugin/issues/209

pulling out the functions parsing to a separate file also helps us write other functionality.

image

**- Description for the changelog**

run `ntl functions:list` to see your locally correctly configured functions.

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by DavidWells** [comment]
Looks good. We should probably add one more column here: `Live` (or whatever word)

The `live` column is true/false and specifies if the function is currenly live on the site or just local (undeployed) right now.

The live functions are included in the https://open-api.netlify.com/#/default/getSite endpoint

Example https://github.com/netlify-labs/oauth-example/blob/master/src/App.js#L155-L156

**Comment by sw-yx** [comment]
the word `live` i think collides with `netlify dev --live`. i'd go for `deployed` altho its longer

cool, TIL you added the Functions thing

**Comment by sw-yx** [comment]
image
hmm, this swagger doesnt seem to have the `available_functions` that you us

**Comment by sw-yx** [comment]
added the deployment check 
image

**Comment by sw-yx** [comment]
reverted to table format. chalk seems to mess it up so i opted to remove chalk.
image

**Comment by DavidWells** [comment]
nice! Looks good. 

> hmm, this swagger doesnt seem to have the available_functions that you us

Yes 😢. There is some serious syncing that needs to happen with API & the API spec.

**Comment by sw-yx** [comment]
> There is some serious syncing that needs to happen with API & the API spec.

GRAPHQL ALL THE THINGS

swagger is so 2018

**Pull request merged**
