### PR TITLE
Handle binary request body using buffer: intends to fix #143

### LINKED ISSUE #143: Bug: netlify dev mangles base64 upload
**- What is the current behavior?**

Binary file upload base64 is mangled when uploaded to netlify dev. The same upload to a deployed site works correctly. The binary is a transparant png for demo purposes:

```bash
$ base64 pixel-transparent.png
iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5CYII=
```

The function just displays the base64 data that is made available:

```javascript
exports.handler = async function (event, context) {
    return {
        statusCode: 200,
        body: JSON.stringify({
            base64: event.isBase64Encoded,
            data: event.body,
        }),
    };
};
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

Upload to netlify dev site:

```bash
$ curl -X POST -H "Content-Type: image/jpeg" --data-binary "@pixel-transparent.png" http://localhost:8888/.netlify/functions/body
{"base64":true,"data":"77+9UE5HDQoaCgAAAA1JSERSAAAAAQAAAAEIBAAAAO+/vRwMAgAAAAtJREFUeO+/vWPvv73vv70AAAIHAQLvv70cMXEAAAAASUVORO+/vUJg77+9"}
```

**- What is the expected behavior?**

Upload to deployed site:

```bash
$ curl -X POST -H "Content-Type: image/jpeg" --data-binary "@pixel-transparent.png" https://{site_id}.netlify.com/.netlify/functions/body
{"base64":true,"data":"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5C"}
```

OS: mac
Node: v10.11.0

Thanks for making Netlify!
Works great :)

### PR DESCRIPTION
**Pull request by sanderhahn**
**- Summary**

Binary bodies where mangled by utf-8 encoding. Now we try to use the bodyParser.raw for binary and bodyParser.text for textual content.

**- Test plan**

My tests are mainly the actions described in issue #143.

**- Description for the changelog**

handle binary request body using buffer

**- A picture of a cute animal (not mandatory but encouraged)**

https://www.youtube.com/watch?v=BjkuMFZBJ3k

### CODE REVIEW

**Comment by sw-yx** [comment]
thank you! the team will review - might not merge soon but definitely appreciated.

**Comment by sanderhahn** [comment]
Thanks, no problem :)

**Comment by mjm** [comment]
I'd love to see this merged! I was hitting this issue when testing locally and thought I might be blocked before realizing this was only a local issue.

**Comment by mjm** [comment]
Thank you!!

**Comment by sw-yx** [comment]
no, thank you! will release soon.

**Comment by sw-yx** [comment]
https://github.com/netlify/cli/releases/tag/v2.11.13

**Pull request merged**
